### ISSUE TITLE
Debian 8 Build is actually Ubuntu 16

### ISSUE THREAD

**Issue by rallytime** [cachedout/barnacle#7]
As seen in the Dockerfile for the debina8 directory: https://github.com/cachedout/barnacle/blob/bb26a57645efdb61300a83717f3ea5e81f4748e4/debian8/Dockerfile#L1

**Comment by Ch3LL** [comment]
oh nice catch! I didn't see that :+1:

**Comment by rallytime** [comment]
yeah should be easy to fix. I just didn't have time to grab it just yet and didn't want to forget!

**Comment by rallytime** [comment]
Thanks Mike!
